### ISSUE TITLE
The project is not starting

### ISSUE THREAD

**Issue by Spectre2004** [mako1601/VoxelWorld#2]
I cloned repo and got error "System.DllNotFoundException: 'Unable to load DLL 'freetype6' or one of its dependencies: The specified module was not found. (0x8007007E)". I placed the file freetype6.dll wherever it could be found but it didn't help.

**Comment by mako1601** [comment]
Привет, какая у тебя операционная система, её разрядность и какой софт ты используешь для сборки?

Проблема возникает в файле Text.cs, 27 строка. 
![devenv_hkvhQ2Ye24](https://github.com/user-attachments/assets/b90b23d7-80ae-40ac-8dc1-987d729b5c92)
Из-за того, что SharpFont просто использует готовый dll файл, и это большая проблема. Я могу посоветовать поискать подходящий для тебя dll файл в интернете и, может быть, есть решения твоей проблемы здесь: https://github.com/Robmaister/SharpFont

В идеале нужно отказаться от этой библиотеки и использовать альтернативы.

**Comment by Spectre2004** [comment]
Привет, использую Visual Studio 2022 Preview, Windows 11 64 битная. Да ошибка именно в том месте как на скриншоте. Т.е. мне нужно вместо freetype6.dll искать другой файл? Какие альтернативы можешь подсказать?

**Comment by mako1601** [comment]
Пробуй искать здесь нужный тебе dll файл: https://github.com/Robmaister/SharpFont.Dependencies/tree/f8b032e132b7319099c916b78ec131866997f643/freetype2

Также я попробовал скачать 32bit dll файл, выдало код ошибки 0x8007000B.
И попробовал случайный (не по ссылке) 64bit dll, такой же код ошибки.

Но твой код ошибки - это конкретно отсутствие файла, он должен быть в папке с sln файлом.

Если все равно не получится запустить, то закомментируй 31 строку UI.cs

Возможной альтернативой для SharpFont может быть https://github.com/ryancheung/FreeTypeSharp. По крайней мере, она так выглядит.

**Comment by Spectre2004** [comment]
https://github.com/Robmaister/SharpFont.Dependencies/tree/f8b032e132b7319099c916b78ec131866997f643/freetype2/2.6/msvc12/x64
вот этот вариант заработал, все запустилось, но теперь F11 не работает)

**Comment by mako1601** [comment]
Это уже не ко мне, а к людям которые пишут OpenTK.

Например, у меня начиная с OpenTK 4.7.x перестал работать метод GL.LineWidth(float), какое значение я бы ни вносил, всегда будет 1.

**Comment by Spectre2004** [comment]
Попробую разобраться, если что то найду напишу.

Еще у меня не работает F3, R, G, B. И как включить мир с процедурной генерацией?

**Comment by mako1601** [comment]
у тебя какой комит?

**Comment by Spectre2004** [comment]
Забыл спулить 😅. Теперь и F11 и все остальное заработало.
